### ISSUE TITLE
请问能否共享一份您之前爬取的法定传染病月报数据？

### ISSUE THREAD

**Issue by yeureka** [madlogos/Shared_Doc#1]
madlogos您好，我想做一个全国法定传染病报告发病和死亡的数据可视化视频，发现中国疾控官网改版以后之前很多word格式的文件都不能下载了，大概11 10年之前数据好多已经不能下载了。我看到您爬过这些数据，请问这些数据还有么？能否给我共享一份 :-) ，如能提供，万分感谢！！！[抱拳]
我的邮箱：yeurekaw@gmail.com

**Comment by madlogos** [comment]
抱歉，因为换了一次电脑，很多资料都挪动了。找了一下，你说的那批数据已经没了，当时觉得保留下来意义不大，就没留。

**Comment by yeureka** [comment]
哦哦，好滴，那太遗憾了，还是感谢啦🙏。
